# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=3.3.4.5
last_mod_version=3.3.4.4

# Common
minecraft_version=1.21.8
mixin_extras_version=0.3.5
whitenoise_version=1.1.1
whitenoise_range=[1.0.0,2.0.0)
mixin_version=0.8.5
# https://minecraft.wiki/w/Pack_format
pack_format=64
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2025.07.20

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.8.47
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.8, 1.21.9)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.133.4+1.21.8
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["1.21.8","1.21.9"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=15.0.0

# Integration and Testing Mods

# Mod options
mod_display_name=Better Days
mod_name=BetterDays
mod_id=betterdays
mod_author=wendall911
license=LGPL-3.0-or-later
mod_description=Gives you control over the passage of time by allowing you to customize the length of the day-night cycle and alters the Minecraft sleep mechanic by accelerating the speed of time.
mod_credits=DuckyCrayfish, Illusive Soulworks
issue_tracker=https://github.com/wendall911/BetterDays/issues
mod_url=https://github.com/wendall911/BetterDays
mod_update_branch=1.21

# CurseForge/Modrinth Options
curseforge_api_key_prop=bdcurseApiKey
curseforge_id=895618
curseforge_slug=betterdays
modrinth_api_key_prop=modrinthKey
modrinth_id=tPLE214j
discord_webhook_prop=bdDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.21.8
